package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.TreeColumn;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetAlignmentSwitch extends WidgetSwitch<Integer> {
	public Integer getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Integer caseCLabel(CLabel widget){
		return widget.getAlignment();
	}
	public Integer caseStyledText(StyledText widget){
		return widget.getAlignment();
	}
	public Integer caseButton(Button widget){
		return widget.getAlignment();
	}
	public Integer caseLabel(Label widget){
		return widget.getAlignment();
	}
	public Integer caseTableColumn(TableColumn widget){
		return widget.getAlignment();
	}
	public Integer caseTreeColumn(TreeColumn widget){
		return widget.getAlignment();
	}
}
    