package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetBackgroundImageSwitch extends WidgetSwitch<Image> {
	public Image getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Image caseScrolledForm(ScrolledForm widget){
		return widget.getBackgroundImage();
	}
	public Image caseForm(Form widget){
		return widget.getBackgroundImage();
	}
	public Image caseControl(Control widget){
		return widget.getBackgroundImage();
	}
}
    