package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.CoolItem;
import org.eclipse.swt.widgets.ExpandItem;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.swt.widgets.ToolItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetControlSwitch extends WidgetSwitch<Control> {
	public Control getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Control caseCTabItem(CTabItem widget){
		return widget.getControl();
	}
	public Control caseCoolItem(CoolItem widget){
		return widget.getControl();
	}
	public Control caseExpandItem(ExpandItem widget){
		return widget.getControl();
	}
	public Control caseTabItem(TabItem widget){
		return widget.getControl();
	}
	public Control caseToolItem(ToolItem widget){
		return widget.getControl();
	}
}
    