package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Cursor;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetCursorSwitch extends WidgetSwitch<Cursor> {
	public Cursor getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Cursor caseControl(Control widget){
		return widget.getCursor();
	}
}
    