package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Menu;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetDefaultItemSwitch extends WidgetSwitch<MenuItem> {
	public MenuItem getProperty(Widget widget){
		return doSwitch(widget);
	}

	public MenuItem caseMenu(Menu widget){
		return widget.getDefaultItem();
	}
}
    