package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Decorations;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetDefaultButtonSwitch extends WidgetSwitch<Button> {
	public Button getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Button caseDecorations(Decorations widget){
		return widget.getDefaultButton();
	}
}
    