package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Slider;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.ScrollBar;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetEnabledSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseShell(Shell widget){
		return widget.getEnabled();
	}
	public Boolean caseSlider(Slider widget){
		return widget.getEnabled();
	}
	public Boolean caseControl(Control widget){
		return widget.getEnabled();
	}
	public Boolean caseMenuItem(MenuItem widget){
		return widget.getEnabled();
	}
	public Boolean caseToolItem(ToolItem widget){
		return widget.getEnabled();
	}
	public Boolean caseMenu(Menu widget){
		return widget.getEnabled();
	}
	public Boolean caseScrollBar(ScrollBar widget){
		return widget.getEnabled();
	}
}
    