/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.Shell;
import java.lang.Boolean;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.ScrollBar;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.MenuItem;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetEnabledSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseShell(Shell widget){
		return widget.isEnabled();
	}
	public Boolean caseControl(Control widget){
		return widget.isEnabled();
	}
	public Boolean caseMenuItem(MenuItem widget){
		return widget.isEnabled();
	}
	public Boolean caseToolItem(ToolItem widget){
		return widget.isEnabled();
	}
	public Boolean caseMenu(Menu widget){
		return widget.isEnabled();
	}
	public Boolean caseScrollBar(ScrollBar widget){
		return widget.isEnabled();
	}
}
    