/*
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.widgets.Caret;
import kr.or.eclipse.swt.query.util.WidgetSwitch;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetFontSwitch extends WidgetSwitch<Font> {
	public Font getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Font caseCaret(Caret widget){
		return widget.getFont();
	}
	public Font caseControl(Control widget){
		return widget.getFont();
	}
	public Font caseCTabItem(CTabItem widget){
		return widget.getFont();
	}
	public Font caseTableItem(TableItem widget){
		return widget.getFont();
	}
	public Font caseTreeItem(TreeItem widget){
		return widget.getFont();
	}
}
    