package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.ui.forms.HyperlinkSettings;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.ui.forms.widgets.FormText;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetHyperlinkSettingsSwitch extends WidgetSwitch<HyperlinkSettings> {
	public HyperlinkSettings getProperty(Widget widget){
		return doSwitch(widget);
	}

	public HyperlinkSettings caseFormText(FormText widget){
		return widget.getHyperlinkSettings();
	}
}
    