package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.IME;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Canvas;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetIMESwitch extends WidgetSwitch<IME> {
	public IME getProperty(Widget widget){
		return doSwitch(widget);
	}

	public IME caseCanvas(Canvas widget){
		return widget.getIME();
	}
}
    