package kr.or.eclipse.swt.query.util.internal;

import java.lang.String;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.List;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetItemsSwitch extends WidgetSwitch<String[]> {
	public String[] getProperty(Widget widget){
		return doSwitch(widget);
	}

	public String[] caseCCombo(CCombo widget){
		return widget.getItems();
	}
	public String[] caseCombo(Combo widget){
		return widget.getItems();
	}
	public String[] caseList(List widget){
		return widget.getItems();
	}
}
    