/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TableItem;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.Item;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.ui.forms.widgets.ImageHyperlink;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.ui.forms.widgets.Form;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetImageSwitch extends WidgetSwitch<Image> {
	public Image getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Image caseCaret(Caret widget){
		return widget.getImage();
	}
	public Image caseImageHyperlink(ImageHyperlink widget){
		return widget.getImage();
	}
	public Image caseScrolledForm(ScrolledForm widget){
		return widget.getImage();
	}
	public Image caseCLabel(CLabel widget){
		return widget.getImage();
	}
	public Image caseDecorations(Decorations widget){
		return widget.getImage();
	}
	public Image caseForm(Form widget){
		return widget.getImage();
	}
	public Image caseButton(Button widget){
		return widget.getImage();
	}
	public Image caseLabel(Label widget){
		return widget.getImage();
	}
	public Image caseTableItem(TableItem widget){
		return widget.getImage();
	}
	public Image caseTreeItem(TreeItem widget){
		return widget.getImage();
	}
	public Image caseItem(Item widget){
		return widget.getImage();
	}
}
    