package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.ui.dialogs.FilteredList;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetLabelProviderSwitch extends WidgetSwitch<ILabelProvider> {
	public ILabelProvider getProperty(Widget widget){
		return doSwitch(widget);
	}

	public ILabelProvider caseFilteredList(FilteredList widget){
		return widget.getLabelProvider();
	}
}
    