package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Layout;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Composite;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetLayoutSwitch extends WidgetSwitch<Layout> {
	public Layout getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Layout caseComposite(Composite widget){
		return widget.getLayout();
	}
}
    