package kr.or.eclipse.swt.query.util.internal;

import java.lang.String;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.widgets.Text;
import org.eclipse.swt.widgets.ToolTip;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetMessageSwitch extends WidgetSwitch<String> {
	public String getProperty(Widget widget){
		return doSwitch(widget);
	}

	public String caseForm(Form widget){
		return widget.getMessage();
	}
	public String caseText(Text widget){
		return widget.getMessage();
	}
	public String caseToolTip(ToolTip widget){
		return widget.getMessage();
	}
}
    