package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Point;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.CoolItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetPreferredSizeSwitch extends WidgetSwitch<Point> {
	public Point getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Point caseCoolItem(CoolItem widget){
		return widget.getPreferredSize();
	}
}
    