package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Tracker;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetRectanglesSwitch extends WidgetSwitch<Rectangle[]> {
	public Rectangle[] getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Rectangle[] caseTracker(Tracker widget){
		return widget.getRectangles();
	}
}
    