/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.browser.Browser;
import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.custom.CLabel;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CTabFolder;
import org.eclipse.swt.custom.SashForm;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetStyleSwitch extends WidgetSwitch<Integer> {
	public Integer getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Integer caseCLabel(CLabel widget){
		return widget.getStyle();
	}
	public Integer caseBrowser(Browser widget){
		return widget.getStyle();
	}
	public Integer caseCCombo(CCombo widget){
		return widget.getStyle();
	}
	public Integer caseCTabFolder(CTabFolder widget){
		return widget.getStyle();
	}
	public Integer caseSashForm(SashForm widget){
		return widget.getStyle();
	}
	public Integer caseWidget(Widget widget){
		return widget.getStyle();
	}
}
    