/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.CoolItem;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.graphics.Point;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetSizeSwitch extends WidgetSwitch<Point> {
	public Point getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Point caseCaret(Caret widget){
		return widget.getSize();
	}
	public Point caseShell(Shell widget){
		return widget.getSize();
	}
	public Point caseDecorations(Decorations widget){
		return widget.getSize();
	}
	public Point caseControl(Control widget){
		return widget.getSize();
	}
	public Point caseCoolItem(CoolItem widget){
		return widget.getSize();
	}
}
    