package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.CTabFolder;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetSelectionForegroundSwitch extends WidgetSwitch<Color> {
	public Color getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Color caseStyledText(StyledText widget){
		return widget.getSelectionForeground();
	}
	public Color caseCTabFolder(CTabFolder widget){
		return widget.getSelectionForeground();
	}
}
    