/*
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.swt.widgets.TrayItem;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.ui.forms.widgets.Hyperlink;
import org.eclipse.swt.widgets.TreeColumn;
import org.eclipse.swt.widgets.TableColumn;
import java.lang.String;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.custom.CLabel;
import kr.or.eclipse.swt.query.util.WidgetSwitch;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetToolTipTextSwitch extends WidgetSwitch<String> {
	public String getProperty(Widget widget){
		return doSwitch(widget);
	}

	public String caseHyperlink(Hyperlink widget){
		return widget.getToolTipText();
	}
	public String caseCLabel(CLabel widget){
		return widget.getToolTipText();
	}
	public String caseControl(Control widget){
		return widget.getToolTipText();
	}
	public String caseCTabItem(CTabItem widget){
		return widget.getToolTipText();
	}
	public String caseTabItem(TabItem widget){
		return widget.getToolTipText();
	}
	public String caseTableColumn(TableColumn widget){
		return widget.getToolTipText();
	}
	public String caseToolItem(ToolItem widget){
		return widget.getToolTipText();
	}
	public String caseTrayItem(TrayItem widget){
		return widget.getToolTipText();
	}
	public String caseTreeColumn(TreeColumn widget){
		return widget.getToolTipText();
	}
}
    