package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Tree;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetTopItemSwitch extends WidgetSwitch<TreeItem> {
	public TreeItem getProperty(Widget widget){
		return doSwitch(widget);
	}

	public TreeItem caseTree(Tree widget){
		return widget.getTopItem();
	}
}
    