package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.List;
import org.eclipse.swt.widgets.Text;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetTopIndexSwitch extends WidgetSwitch<Integer> {
	public Integer getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Integer caseStyledText(StyledText widget){
		return widget.getTopIndex();
	}
	public Integer caseTable(Table widget){
		return widget.getTopIndex();
	}
	public Integer caseList(List widget){
		return widget.getTopIndex();
	}
	public Integer caseText(Text widget){
		return widget.getTopIndex();
	}
}
    