package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetBoundsSwitch extends WidgetSwitchWithArgument<Object, Rectangle> {
	public void setProperty(Widget widget, Rectangle value){
		doSwitch(widget, value);
	}

	public Object caseCaret(Caret widget, Rectangle value){
		widget.setBounds(value);
		return null;
	}
	public Object caseShell(Shell widget, Rectangle value){
		widget.setBounds(value);
		return null;
	}
	public Object caseDecorations(Decorations widget, Rectangle value){
		widget.setBounds(value);
		return null;
	}
	public Object caseControl(Control widget, Rectangle value){
		widget.setBounds(value);
		return null;
	}
}
    