package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.CoolItem;
import org.eclipse.swt.widgets.ExpandItem;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.swt.widgets.ToolItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetControlSwitch extends WidgetSwitchWithArgument<Object, Control> {
	public void setProperty(Widget widget, Control value){
		doSwitch(widget, value);
	}

	public Object caseCTabItem(CTabItem widget, Control value){
		widget.setControl(value);
		return null;
	}
	public Object caseCoolItem(CoolItem widget, Control value){
		widget.setControl(value);
		return null;
	}
	public Object caseExpandItem(ExpandItem widget, Control value){
		widget.setControl(value);
		return null;
	}
	public Object caseTabItem(TabItem widget, Control value){
		widget.setControl(value);
		return null;
	}
	public Object caseToolItem(ToolItem widget, Control value){
		widget.setControl(value);
		return null;
	}
}
    