package kr.or.eclipse.swt.query.util.internal;


import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.Tree;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetColumnOrderSwitch extends WidgetSwitchWithArgument<Object, int[]> {
	public void setProperty(Widget widget, int[] value){
		doSwitch(widget, value);
	}

	public Object caseTable(Table widget, int[] value){
		widget.setColumnOrder(value);
		return null;
	}
	public Object caseTree(Tree widget, int[] value){
		widget.setColumnOrder(value);
		return null;
	}
}
    