package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Decorations;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetDefaultButtonSwitch extends WidgetSwitchWithArgument<Object, Button> {
	public void setProperty(Widget widget, Button value){
		doSwitch(widget, value);
	}

	public Object caseDecorations(Decorations widget, Button value){
		widget.setDefaultButton(value);
		return null;
	}
}
    