package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Menu;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetDefaultItemSwitch extends WidgetSwitchWithArgument<Object, MenuItem> {
	public void setProperty(Widget widget, MenuItem value){
		doSwitch(widget, value);
	}

	public Object caseMenu(Menu widget, MenuItem value){
		widget.setDefaultItem(value);
		return null;
	}
}
    