package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.dnd.DropTargetEffect;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.dnd.DropTarget;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetDropTargetEffectSwitch extends WidgetSwitchWithArgument<Object, DropTargetEffect> {
	public void setProperty(Widget widget, DropTargetEffect value){
		doSwitch(widget, value);
	}

	public Object caseDropTarget(DropTarget widget, DropTargetEffect value){
		widget.setDropTargetEffect(value);
		return null;
	}
}
    