package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.dnd.DragSourceEffect;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.dnd.DragSource;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetDragSourceEffectSwitch extends WidgetSwitchWithArgument<Object, DragSourceEffect> {
	public void setProperty(Widget widget, DragSourceEffect value){
		doSwitch(widget, value);
	}

	public Object caseDragSource(DragSource widget, DragSourceEffect value){
		widget.setDragSourceEffect(value);
		return null;
	}
}
    