package kr.or.eclipse.swt.query.util.internal;

import java.lang.Character;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Text;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetEchoCharSwitch extends WidgetSwitchWithArgument<Object, Character> {
	public void setProperty(Widget widget, Character value){
		doSwitch(widget, value);
	}

	public Object caseText(Text widget, Character value){
		widget.setEchoChar(value);
		return null;
	}
}
    