package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.ui.forms.widgets.FormText;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.ui.forms.widgets.ScrolledFormText;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetFormTextSwitch extends WidgetSwitchWithArgument<Object, FormText> {
	public void setProperty(Widget widget, FormText value){
		doSwitch(widget, value);
	}

	public Object caseScrolledFormText(ScrolledFormText widget, FormText value){
		widget.setFormText(value);
		return null;
	}
}
    