package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetGrayedSwitch extends WidgetSwitchWithArgument<Object, Boolean> {
	public void setProperty(Widget widget, Boolean value){
		doSwitch(widget, value);
	}

	public Object caseButton(Button widget, Boolean value){
		widget.setGrayed(value);
		return null;
	}
	public Object caseTableItem(TableItem widget, Boolean value){
		widget.setGrayed(value);
		return null;
	}
	public Object caseTreeItem(TreeItem widget, Boolean value){
		widget.setGrayed(value);
		return null;
	}
}
    