package kr.or.eclipse.swt.query.util.internal;

import java.lang.String;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.List;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetItemsSwitch extends WidgetSwitchWithArgument<Object, String[]> {
	public void setProperty(Widget widget, String[] value){
		doSwitch(widget, value);
	}

	public Object caseCCombo(CCombo widget, String[] value){
		widget.setItems(value);
		return null;
	}
	public Object caseCombo(Combo widget, String[] value){
		widget.setItems(value);
		return null;
	}
	public Object caseList(List widget, String[] value){
		widget.setItems(value);
		return null;
	}
}
    