package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.ui.dialogs.FilteredList;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetLabelProviderSwitch extends WidgetSwitchWithArgument<Object, ILabelProvider> {
	public void setProperty(Widget widget, ILabelProvider value){
		doSwitch(widget, value);
	}

	public Object caseFilteredList(FilteredList widget, ILabelProvider value){
		widget.setLabelProvider(value);
		return null;
	}
}
    