package kr.or.eclipse.swt.query.util.internal;

import java.lang.Object;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetLayoutDataSwitch extends WidgetSwitchWithArgument<Object, Object> {
	public void setProperty(Widget widget, Object value){
		doSwitch(widget, value);
	}

	public Object caseControl(Control widget, Object value){
		widget.setLayoutData(value);
		return null;
	}
}
    