package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Combo;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetListVisibleSwitch extends WidgetSwitchWithArgument<Object, Boolean> {
	public void setProperty(Widget widget, Boolean value){
		doSwitch(widget, value);
	}

	public Object caseCCombo(CCombo widget, Boolean value){
		widget.setListVisible(value);
		return null;
	}
	public Object caseCombo(Combo widget, Boolean value){
		widget.setListVisible(value);
		return null;
	}
}
    