package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Spinner;
import org.eclipse.swt.widgets.ProgressBar;
import org.eclipse.swt.widgets.Scale;
import org.eclipse.swt.widgets.Slider;
import org.eclipse.swt.widgets.ScrollBar;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetMaximumSwitch extends WidgetSwitchWithArgument<Object, Integer> {
	public void setProperty(Widget widget, Integer value){
		doSwitch(widget, value);
	}

	public Object caseSpinner(Spinner widget, Integer value){
		widget.setMaximum(value);
		return null;
	}
	public Object caseProgressBar(ProgressBar widget, Integer value){
		widget.setMaximum(value);
		return null;
	}
	public Object caseScale(Scale widget, Integer value){
		widget.setMaximum(value);
		return null;
	}
	public Object caseSlider(Slider widget, Integer value){
		widget.setMaximum(value);
		return null;
	}
	public Object caseScrollBar(ScrollBar widget, Integer value){
		widget.setMaximum(value);
		return null;
	}
}
    