package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Point;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.CBanner;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetRightMinimumSizeSwitch extends WidgetSwitchWithArgument<Object, Point> {
	public void setProperty(Widget widget, Point value){
		doSwitch(widget, value);
	}

	public Object caseCBanner(CBanner widget, Point value){
		widget.setRightMinimumSize(value);
		return null;
	}
}
    