package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Region;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetRegionSwitch extends WidgetSwitchWithArgument<Object, Region> {
	public void setProperty(Widget widget, Region value){
		doSwitch(widget, value);
	}

	public Object caseShell(Shell widget, Region value){
		widget.setRegion(value);
		return null;
	}
	public Object caseControl(Control widget, Region value){
		widget.setRegion(value);
		return null;
	}
}
    