package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.Tree;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetSortDirectionSwitch extends WidgetSwitchWithArgument<Object, Integer> {
	public void setProperty(Widget widget, Integer value){
		doSwitch(widget, value);
	}

	public Object caseTable(Table widget, Integer value){
		widget.setSortDirection(value);
		return null;
	}
	public Object caseTree(Tree widget, Integer value){
		widget.setSortDirection(value);
		return null;
	}
}
    