package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.CTabFolder;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetSelectionBackgroundSwitch extends WidgetSwitchWithArgument<Object, Color> {
	public void setProperty(Widget widget, Color value){
		doSwitch(widget, value);
	}

	public Object caseStyledText(StyledText widget, Color value){
		widget.setSelectionBackground(value);
		return null;
	}
	public Object caseCTabFolder(CTabFolder widget, Color value){
		widget.setSelectionBackground(value);
		return null;
	}
}
    