/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.Link;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.ui.forms.widgets.Hyperlink;
import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.widgets.Item;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.ui.forms.widgets.ExpandableComposite;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.ToolTip;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.custom.StyledText;
import java.lang.String;
import org.eclipse.swt.widgets.Combo;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Text;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class SetTextSwitch extends WidgetSwitchWithArgument<Object, String> {
	public void setProperty(Widget widget, String value){
		doSwitch(widget, value);
	}

	public Object caseHyperlink(Hyperlink widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseScrolledForm(ScrolledForm widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseCLabel(CLabel widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseStyledText(StyledText widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseDecorations(Decorations widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseExpandableComposite(ExpandableComposite widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseBrowser(Browser widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseCCombo(CCombo widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseCombo(Combo widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseGroup(Group widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseForm(Form widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseText(Text widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseButton(Button widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseLabel(Label widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseLink(Link widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseTableItem(TableItem widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseTreeItem(TreeItem widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseItem(Item widget, String value){
		widget.setText(value);
		return null;
	}
	public Object caseToolTip(ToolTip widget, String value){
		widget.setText(value);
		return null;
	}
}
    