package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.dnd.Transfer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.dnd.DragSource;
import org.eclipse.swt.dnd.DropTarget;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetTransferSwitch extends WidgetSwitchWithArgument<Object, Transfer[]> {
	public void setProperty(Widget widget, Transfer[] value){
		doSwitch(widget, value);
	}

	public Object caseDragSource(DragSource widget, Transfer[] value){
		widget.setTransfer(value);
		return null;
	}
	public Object caseDropTarget(DropTarget widget, Transfer[] value){
		widget.setTransfer(value);
		return null;
	}
}
    