package kr.or.eclipse.swt.query.util.internal;

import java.lang.String;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.ui.forms.widgets.Hyperlink;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.TrayItem;
import org.eclipse.swt.widgets.TreeColumn;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetToolTipTextSwitch extends WidgetSwitchWithArgument<Object, String> {
	public void setProperty(Widget widget, String value){
		doSwitch(widget, value);
	}

	public Object caseHyperlink(Hyperlink widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseCLabel(CLabel widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseControl(Control widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseCTabItem(CTabItem widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseTabItem(TabItem widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseTableColumn(TableColumn widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseToolItem(ToolItem widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseTrayItem(TrayItem widget, String value){
		widget.setToolTipText(value);
		return null;
	}
	public Object caseTreeColumn(TreeColumn widget, String value){
		widget.setToolTipText(value);
		return null;
	}
}
    