package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Tree;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetTopItemSwitch extends WidgetSwitchWithArgument<Object, TreeItem> {
	public void setProperty(Widget widget, TreeItem value){
		doSwitch(widget, value);
	}

	public Object caseTree(Tree widget, TreeItem value){
		widget.setTopItem(value);
		return null;
	}
}
    