package kr.or.eclipse.swt.query.util.internal;

import java.lang.String;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.browser.Browser;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetUrlSwitch extends WidgetSwitchWithArgument<Object, String> {
	public void setProperty(Widget widget, String value){
		doSwitch(widget, value);
	}

	public Object caseBrowser(Browser widget, String value){
		widget.setUrl(value);
		return null;
	}
}
    