package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.TreeColumn;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetWidthSwitch extends WidgetSwitchWithArgument<Object, Integer> {
	public void setProperty(Widget widget, Integer value){
		doSwitch(widget, value);
	}

	public Object caseTableColumn(TableColumn widget, Integer value){
		widget.setWidth(value);
		return null;
	}
	public Object caseToolItem(ToolItem widget, Integer value){
		widget.setWidth(value);
		return null;
	}
	public Object caseTreeColumn(TreeColumn widget, Integer value){
		widget.setWidth(value);
		return null;
	}
}
    