/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.swt.widgets.CoolItem;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.graphics.Rectangle;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetBoundsSwitch extends WidgetSwitch<Rectangle> {
	public Rectangle getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Rectangle caseCaret(Caret widget){
		return widget.getBounds();
	}
	public Rectangle caseShell(Shell widget){
		return widget.getBounds();
	}
	public Rectangle caseDecorations(Decorations widget){
		return widget.getBounds();
	}
	public Rectangle caseControl(Control widget){
		return widget.getBounds();
	}
	public Rectangle caseCTabItem(CTabItem widget){
		return widget.getBounds();
	}
	public Rectangle caseCoolItem(CoolItem widget){
		return widget.getBounds();
	}
	public Rectangle caseTabItem(TabItem widget){
		return widget.getBounds();
	}
	public Rectangle caseTableItem(TableItem widget){
		return widget.getBounds();
	}
	public Rectangle caseToolItem(ToolItem widget){
		return widget.getBounds();
	}
	public Rectangle caseTreeItem(TreeItem widget){
		return widget.getBounds();
	}
}
    