package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetBoundsSwitch extends WidgetSwitch<Rectangle> {
	public Rectangle getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Rectangle caseCaret(Caret widget){
		return widget.getBounds();
	}
	public Rectangle caseShell(Shell widget){
		return widget.getBounds();
	}
	public Rectangle caseDecorations(Decorations widget){
		return widget.getBounds();
	}
	public Rectangle caseControl(Control widget){
		return widget.getBounds();
	}
}
    