package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Canvas;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetCaretSwitch extends WidgetSwitch<Caret> {
	public Caret getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Caret caseCanvas(Canvas widget){
		return widget.getCaret();
	}
}
    