package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.dnd.DropTargetEffect;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.dnd.DropTarget;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetDropTargetEffectSwitch extends WidgetSwitch<DropTargetEffect> {
	public DropTargetEffect getProperty(Widget widget){
		return doSwitch(widget);
	}

	public DropTargetEffect caseDropTarget(DropTarget widget){
		return widget.getDropTargetEffect();
	}
}
    