package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Text;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetEditableSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseStyledText(StyledText widget){
		return widget.getEditable();
	}
	public Boolean caseCCombo(CCombo widget){
		return widget.getEditable();
	}
	public Boolean caseText(Text widget){
		return widget.getEditable();
	}
}
    