package kr.or.eclipse.swt.query.util.internal;

import java.lang.Character;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Text;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetEchoCharSwitch extends WidgetSwitch<Character> {
	public Character getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Character caseText(Text widget){
		return widget.getEchoChar();
	}
}
    