package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.ExpandItem;
import org.eclipse.swt.widgets.TreeItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetExpandedSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseExpandItem(ExpandItem widget){
		return widget.getExpanded();
	}
	public Boolean caseTreeItem(TreeItem widget){
		return widget.getExpanded();
	}
}
    