package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.ui.forms.widgets.FormText;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.ui.forms.widgets.ScrolledFormText;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetFormTextSwitch extends WidgetSwitch<FormText> {
	public FormText getProperty(Widget widget){
		return doSwitch(widget);
	}

	public FormText caseScrolledFormText(ScrolledFormText widget){
		return widget.getFormText();
	}
}
    