package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetFontSwitch extends WidgetSwitch<Font> {
	public Font getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Font caseCaret(Caret widget){
		return widget.getFont();
	}
	public Font caseControl(Control widget){
		return widget.getFont();
	}
	public Font caseCTabItem(CTabItem widget){
		return widget.getFont();
	}
	public Font caseTableItem(TableItem widget){
		return widget.getFont();
	}
	public Font caseTreeItem(TreeItem widget){
		return widget.getFont();
	}
}
    