package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.TableCursor;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetForegroundSwitch extends WidgetSwitch<Color> {
	public Color getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Color caseStyledText(StyledText widget){
		return widget.getForeground();
	}
	public Color caseTableCursor(TableCursor widget){
		return widget.getForeground();
	}
	public Color caseControl(Control widget){
		return widget.getForeground();
	}
	public Color caseTableItem(TableItem widget){
		return widget.getForeground();
	}
	public Color caseTreeItem(TreeItem widget){
		return widget.getForeground();
	}
}
    