/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Tray;
import org.eclipse.swt.widgets.CoolBar;
import org.eclipse.swt.widgets.Tree;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.List;
import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.ExpandBar;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.custom.CTabFolder;
import org.eclipse.swt.widgets.ToolBar;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.TabFolder;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetItemCountSwitch extends WidgetSwitch<Integer> {
	public Integer getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Integer caseCCombo(CCombo widget){
		return widget.getItemCount();
	}
	public Integer caseCTabFolder(CTabFolder widget){
		return widget.getItemCount();
	}
	public Integer caseCombo(Combo widget){
		return widget.getItemCount();
	}
	public Integer caseCoolBar(CoolBar widget){
		return widget.getItemCount();
	}
	public Integer caseExpandBar(ExpandBar widget){
		return widget.getItemCount();
	}
	public Integer caseTabFolder(TabFolder widget){
		return widget.getItemCount();
	}
	public Integer caseTable(Table widget){
		return widget.getItemCount();
	}
	public Integer caseToolBar(ToolBar widget){
		return widget.getItemCount();
	}
	public Integer caseTree(Tree widget){
		return widget.getItemCount();
	}
	public Integer caseList(List widget){
		return widget.getItemCount();
	}
	public Integer caseTreeItem(TreeItem widget){
		return widget.getItemCount();
	}
	public Integer caseMenu(Menu widget){
		return widget.getItemCount();
	}
	public Integer caseTray(Tray widget){
		return widget.getItemCount();
	}
}
    