package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.ui.forms.widgets.ImageHyperlink;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.Item;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetImageSwitch extends WidgetSwitch<Image> {
	public Image getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Image caseCaret(Caret widget){
		return widget.getImage();
	}
	public Image caseImageHyperlink(ImageHyperlink widget){
		return widget.getImage();
	}
	public Image caseScrolledForm(ScrolledForm widget){
		return widget.getImage();
	}
	public Image caseCLabel(CLabel widget){
		return widget.getImage();
	}
	public Image caseDecorations(Decorations widget){
		return widget.getImage();
	}
	public Image caseForm(Form widget){
		return widget.getImage();
	}
	public Image caseButton(Button widget){
		return widget.getImage();
	}
	public Image caseLabel(Label widget){
		return widget.getImage();
	}
	public Image caseTableItem(TableItem widget){
		return widget.getImage();
	}
	public Image caseTreeItem(TreeItem widget){
		return widget.getImage();
	}
	public Image caseItem(Item widget){
		return widget.getImage();
	}
}
    