package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Combo;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetListVisibleSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseCCombo(CCombo widget){
		return widget.getListVisible();
	}
	public Boolean caseCombo(Combo widget){
		return widget.getListVisible();
	}
}
    