package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.Tree;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetLinesVisibleSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseTable(Table widget){
		return widget.getLinesVisible();
	}
	public Boolean caseTree(Tree widget){
		return widget.getLinesVisible();
	}
}
    