package kr.or.eclipse.swt.query.util.internal;

import java.lang.Object;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetLayoutDataSwitch extends WidgetSwitch<Object> {
	public Object getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Object caseControl(Control widget){
		return widget.getLayoutData();
	}
}
    