package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.MenuItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetMenuSwitch extends WidgetSwitch<Menu> {
	public Menu getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Menu caseCCombo(CCombo widget){
		return widget.getMenu();
	}
	public Menu caseControl(Control widget){
		return widget.getMenu();
	}
	public Menu caseMenuItem(MenuItem widget){
		return widget.getMenu();
	}
}
    