package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Decorations;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetMenuBarSwitch extends WidgetSwitch<Menu> {
	public Menu getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Menu caseDecorations(Decorations widget){
		return widget.getMenuBar();
	}
}
    