package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.custom.CTabFolder;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetMaximizedSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseShell(Shell widget){
		return widget.getMaximized();
	}
	public Boolean caseDecorations(Decorations widget){
		return widget.getMaximized();
	}
	public Boolean caseCTabFolder(CTabFolder widget){
		return widget.getMaximized();
	}
}
    