package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.SashForm;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Text;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetOrientationSwitch extends WidgetSwitch<Integer> {
	public Integer getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Integer caseStyledText(StyledText widget){
		return widget.getOrientation();
	}
	public Integer caseSashForm(SashForm widget){
		return widget.getOrientation();
	}
	public Integer caseCombo(Combo widget){
		return widget.getOrientation();
	}
	public Integer caseText(Text widget){
		return widget.getOrientation();
	}
}
    