package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetParentSwitch extends WidgetSwitch<Composite> {
	public Composite getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Composite caseControl(Control widget){
		return widget.getParent();
	}
}
    