package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Region;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetRegionSwitch extends WidgetSwitch<Region> {
	public Region getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Region caseShell(Shell widget){
		return widget.getRegion();
	}
	public Region caseControl(Control widget){
		return widget.getRegion();
	}
}
    