package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.custom.StyleRange;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.StyledText;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetStyleRangesSwitch extends WidgetSwitch<StyleRange[]> {
	public StyleRange[] getProperty(Widget widget){
		return doSwitch(widget);
	}

	public StyleRange[] caseStyledText(StyledText widget){
		return widget.getStyleRanges();
	}
}
    