/**
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Link;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.ui.forms.widgets.Hyperlink;
import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.widgets.Item;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.widgets.Spinner;
import org.eclipse.ui.forms.widgets.ExpandableComposite;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.swt.widgets.ToolTip;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.custom.StyledText;
import java.lang.String;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Text;
import org.eclipse.swt.widgets.IME;
import org.eclipse.ui.forms.widgets.AbstractHyperlink;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetTextSwitch extends WidgetSwitch<String> {
	public String getProperty(Widget widget){
		return doSwitch(widget);
	}

	public String caseHyperlink(Hyperlink widget){
		return widget.getText();
	}
	public String caseScrolledForm(ScrolledForm widget){
		return widget.getText();
	}
	public String caseCLabel(CLabel widget){
		return widget.getText();
	}
	public String caseStyledText(StyledText widget){
		return widget.getText();
	}
	public String caseDecorations(Decorations widget){
		return widget.getText();
	}
	public String caseAbstractHyperlink(AbstractHyperlink widget){
		return widget.getText();
	}
	public String caseExpandableComposite(ExpandableComposite widget){
		return widget.getText();
	}
	public String caseBrowser(Browser widget){
		return widget.getText();
	}
	public String caseCCombo(CCombo widget){
		return widget.getText();
	}
	public String caseCombo(Combo widget){
		return widget.getText();
	}
	public String caseGroup(Group widget){
		return widget.getText();
	}
	public String caseSpinner(Spinner widget){
		return widget.getText();
	}
	public String caseForm(Form widget){
		return widget.getText();
	}
	public String caseText(Text widget){
		return widget.getText();
	}
	public String caseButton(Button widget){
		return widget.getText();
	}
	public String caseLabel(Label widget){
		return widget.getText();
	}
	public String caseLink(Link widget){
		return widget.getText();
	}
	public String caseIME(IME widget){
		return widget.getText();
	}
	public String caseTableItem(TableItem widget){
		return widget.getText();
	}
	public String caseTreeItem(TreeItem widget){
		return widget.getText();
	}
	public String caseItem(Item widget){
		return widget.getText();
	}
	public String caseToolTip(ToolTip widget){
		return widget.getText();
	}
}
    