package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Composite;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetTabListSwitch extends WidgetSwitch<Control[]> {
	public Control[] getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Control[] caseComposite(Composite widget){
		return widget.getTabList();
	}
}
    