package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.dnd.Transfer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.dnd.DragSource;
import org.eclipse.swt.dnd.DropTarget;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetTransferSwitch extends WidgetSwitch<Transfer[]> {
	public Transfer[] getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Transfer[] caseDragSource(DragSource widget){
		return widget.getTransfer();
	}
	public Transfer[] caseDropTarget(DropTarget widget){
		return widget.getTransfer();
	}
}
    