package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.ToolTip;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.TrayItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetToolTipSwitch extends WidgetSwitch<ToolTip> {
	public ToolTip getProperty(Widget widget){
		return doSwitch(widget);
	}

	public ToolTip caseTrayItem(TrayItem widget){
		return widget.getToolTip();
	}
}
    