/*
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.ScrollBar;
import org.eclipse.swt.widgets.Menu;
import java.lang.Boolean;
import org.eclipse.swt.widgets.TrayItem;
import org.eclipse.swt.widgets.ToolTip;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.widgets.Caret;
import kr.or.eclipse.swt.query.util.WidgetSwitch;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class GetVisibleSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseCaret(Caret widget){
		return widget.getVisible();
	}
	public Boolean caseControl(Control widget){
		return widget.getVisible();
	}
	public Boolean caseTrayItem(TrayItem widget){
		return widget.getVisible();
	}
	public Boolean caseMenu(Menu widget){
		return widget.getVisible();
	}
	public Boolean caseScrollBar(ScrollBar widget){
		return widget.getVisible();
	}
	public Boolean caseToolTip(ToolTip widget){
		return widget.getVisible();
	}
}
    