package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Combo;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetVisibleItemCountSwitch extends WidgetSwitch<Integer> {
	public Integer getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Integer caseCCombo(CCombo widget){
		return widget.getVisibleItemCount();
	}
	public Integer caseCombo(Combo widget){
		return widget.getVisibleItemCount();
	}
}
    