package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitch;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.TrayItem;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.ScrollBar;
import org.eclipse.swt.widgets.ToolTip;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class GetVisibleSwitch extends WidgetSwitch<Boolean> {
	public Boolean getProperty(Widget widget){
		return doSwitch(widget);
	}

	public Boolean caseCaret(Caret widget){
		return widget.getVisible();
	}
	public Boolean caseControl(Control widget){
		return widget.getVisible();
	}
	public Boolean caseTrayItem(TrayItem widget){
		return widget.getVisible();
	}
	public Boolean caseMenu(Menu widget){
		return widget.getVisible();
	}
	public Boolean caseScrollBar(ScrollBar widget){
		return widget.getVisible();
	}
	public Boolean caseToolTip(ToolTip widget){
		return widget.getVisible();
	}
}
    