package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.TreeColumn;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetAlignmentSwitch extends WidgetSwitchWithArgument<Object, Integer> {
	public void setProperty(Widget widget, Integer value){
		doSwitch(widget, value);
	}

	public Object caseCLabel(CLabel widget, Integer value){
		widget.setAlignment(value);
		return null;
	}
	public Object caseStyledText(StyledText widget, Integer value){
		widget.setAlignment(value);
		return null;
	}
	public Object caseButton(Button widget, Integer value){
		widget.setAlignment(value);
		return null;
	}
	public Object caseLabel(Label widget, Integer value){
		widget.setAlignment(value);
		return null;
	}
	public Object caseTableColumn(TableColumn widget, Integer value){
		widget.setAlignment(value);
		return null;
	}
	public Object caseTreeColumn(TreeColumn widget, Integer value){
		widget.setAlignment(value);
		return null;
	}
}
    