package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.TableCursor;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetBackgroundSwitch extends WidgetSwitchWithArgument<Object, Color> {
	public void setProperty(Widget widget, Color value){
		doSwitch(widget, value);
	}

	public Object caseStyledText(StyledText widget, Color value){
		widget.setBackground(value);
		return null;
	}
	public Object caseTableCursor(TableCursor widget, Color value){
		widget.setBackground(value);
		return null;
	}
	public Object caseControl(Control widget, Color value){
		widget.setBackground(value);
		return null;
	}
	public Object caseTableItem(TableItem widget, Color value){
		widget.setBackground(value);
		return null;
	}
	public Object caseTreeItem(TreeItem widget, Color value){
		widget.setBackground(value);
		return null;
	}
}
    