package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Cursor;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetCursorSwitch extends WidgetSwitchWithArgument<Object, Cursor> {
	public void setProperty(Widget widget, Cursor value){
		doSwitch(widget, value);
	}

	public Object caseControl(Control widget, Cursor value){
		widget.setCursor(value);
		return null;
	}
}
    