package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Slider;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.ScrollBar;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetEnabledSwitch extends WidgetSwitchWithArgument<Object, Boolean> {
	public void setProperty(Widget widget, Boolean value){
		doSwitch(widget, value);
	}

	public Object caseShell(Shell widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
	public Object caseSlider(Slider widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
	public Object caseControl(Control widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
	public Object caseMenuItem(MenuItem widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
	public Object caseToolItem(ToolItem widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
	public Object caseMenu(Menu widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
	public Object caseScrollBar(ScrollBar widget, Boolean value){
		widget.setEnabled(value);
		return null;
	}
}
    