/*
 * Copyright 2011 jeeeyul@gmail.com
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 */

package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.TableItem;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Widget;
import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.widgets.Caret;


/*
 * This file was generated by SWT Query SDK.
 * So you should not modify it manually.
 * If you want to customize this code, contact below:
 *
 * http://code.google.com/p/swtquery/
 */
public class SetFontSwitch extends WidgetSwitchWithArgument<Object, Font> {
	public void setProperty(Widget widget, Font value){
		doSwitch(widget, value);
	}

	public Object caseCaret(Caret widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseControl(Control widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseCTabItem(CTabItem widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseTableItem(TableItem widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseTreeItem(TreeItem widget, Font value){
		widget.setFont(value);
		return null;
	}
}
    