package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetFontSwitch extends WidgetSwitchWithArgument<Object, Font> {
	public void setProperty(Widget widget, Font value){
		doSwitch(widget, value);
	}

	public Object caseCaret(Caret widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseControl(Control widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseCTabItem(CTabItem widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseTableItem(TableItem widget, Font value){
		widget.setFont(value);
		return null;
	}
	public Object caseTreeItem(TreeItem widget, Font value){
		widget.setFont(value);
		return null;
	}
}
    