package kr.or.eclipse.swt.query.util.internal;

import java.lang.Object;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.ui.forms.widgets.AbstractHyperlink;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetHrefSwitch extends WidgetSwitchWithArgument<Object, Object> {
	public void setProperty(Widget widget, Object value){
		doSwitch(widget, value);
	}

	public Object caseAbstractHyperlink(AbstractHyperlink widget, Object value){
		widget.setHref(value);
		return null;
	}
}
    