package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.ui.forms.widgets.ImageHyperlink;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.Item;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetImageSwitch extends WidgetSwitchWithArgument<Object, Image> {
	public void setProperty(Widget widget, Image value){
		doSwitch(widget, value);
	}

	public Object caseCaret(Caret widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseImageHyperlink(ImageHyperlink widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseScrolledForm(ScrolledForm widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseCLabel(CLabel widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseDecorations(Decorations widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseForm(Form widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseButton(Button widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseLabel(Label widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseTableItem(TableItem widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseTreeItem(TreeItem widget, Image value){
		widget.setImage(value);
		return null;
	}
	public Object caseItem(Item widget, Image value){
		widget.setImage(value);
		return null;
	}
}
    