package kr.or.eclipse.swt.query.util.internal;

import java.lang.String;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.swt.widgets.Text;
import org.eclipse.swt.widgets.ToolTip;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetMessageSwitch extends WidgetSwitchWithArgument<Object, String> {
	public void setProperty(Widget widget, String value){
		doSwitch(widget, value);
	}

	public Object caseForm(Form widget, String value){
		widget.setMessage(value);
		return null;
	}
	public Object caseText(Text widget, String value){
		widget.setMessage(value);
		return null;
	}
	public Object caseToolTip(ToolTip widget, String value){
		widget.setMessage(value);
		return null;
	}
}
    