package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Decorations;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetMenuBarSwitch extends WidgetSwitchWithArgument<Object, Menu> {
	public void setProperty(Widget widget, Menu value){
		doSwitch(widget, value);
	}

	public Object caseDecorations(Decorations widget, Menu value){
		widget.setMenuBar(value);
		return null;
	}
}
    