package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.SashForm;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.Text;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetOrientationSwitch extends WidgetSwitchWithArgument<Object, Integer> {
	public void setProperty(Widget widget, Integer value){
		doSwitch(widget, value);
	}

	public Object caseStyledText(StyledText widget, Integer value){
		widget.setOrientation(value);
		return null;
	}
	public Object caseSashForm(SashForm widget, Integer value){
		widget.setOrientation(value);
		return null;
	}
	public Object caseCombo(Combo widget, Integer value){
		widget.setOrientation(value);
		return null;
	}
	public Object caseText(Text widget, Integer value){
		widget.setOrientation(value);
		return null;
	}
}
    