package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Control;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetParentSwitch extends WidgetSwitchWithArgument<Object, Composite> {
	public void setProperty(Widget widget, Composite value){
		doSwitch(widget, value);
	}

	public Object caseControl(Control widget, Composite value){
		widget.setParent(value);
		return null;
	}
}
    