package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Tracker;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetRectanglesSwitch extends WidgetSwitchWithArgument<Object, Rectangle[]> {
	public void setProperty(Widget widget, Rectangle[] value){
		doSwitch(widget, value);
	}

	public Object caseTracker(Tracker widget, Rectangle[] value){
		widget.setRectangles(value);
		return null;
	}
}
    