package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.custom.StyleRange;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.StyledText;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetStyleRangesSwitch extends WidgetSwitchWithArgument<Object, StyleRange[]> {
	public void setProperty(Widget widget, StyleRange[] value){
		doSwitch(widget, value);
	}

	public Object caseStyledText(StyledText widget, StyleRange[] value){
		widget.setStyleRanges(value);
		return null;
	}
}
    