package kr.or.eclipse.swt.query.util.internal;

import org.eclipse.swt.widgets.ToolTip;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.TrayItem;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetToolTipSwitch extends WidgetSwitchWithArgument<Object, ToolTip> {
	public void setProperty(Widget widget, ToolTip value){
		doSwitch(widget, value);
	}

	public Object caseTrayItem(TrayItem widget, ToolTip value){
		widget.setToolTip(value);
		return null;
	}
}
    