package kr.or.eclipse.swt.query.util.internal;

import java.lang.Integer;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.widgets.Combo;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetVisibleItemCountSwitch extends WidgetSwitchWithArgument<Object, Integer> {
	public void setProperty(Widget widget, Integer value){
		doSwitch(widget, value);
	}

	public Object caseCCombo(CCombo widget, Integer value){
		widget.setVisibleItemCount(value);
		return null;
	}
	public Object caseCombo(Combo widget, Integer value){
		widget.setVisibleItemCount(value);
		return null;
	}
}
    