package kr.or.eclipse.swt.query.util.internal;

import java.lang.Boolean;
import org.eclipse.swt.widgets.Widget;
import kr.or.eclipse.swt.query.util.WidgetSwitchWithArgument;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.TrayItem;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.ScrollBar;
import org.eclipse.swt.widgets.ToolTip;
/*
 * generated by SWT Query SDK at Mon Oct 24 19:21:20 KST 2011
 */ 
public class SetVisibleSwitch extends WidgetSwitchWithArgument<Object, Boolean> {
	public void setProperty(Widget widget, Boolean value){
		doSwitch(widget, value);
	}

	public Object caseCaret(Caret widget, Boolean value){
		widget.setVisible(value);
		return null;
	}
	public Object caseControl(Control widget, Boolean value){
		widget.setVisible(value);
		return null;
	}
	public Object caseTrayItem(TrayItem widget, Boolean value){
		widget.setVisible(value);
		return null;
	}
	public Object caseMenu(Menu widget, Boolean value){
		widget.setVisible(value);
		return null;
	}
	public Object caseScrollBar(ScrollBar widget, Boolean value){
		widget.setVisible(value);
		return null;
	}
	public Object caseToolTip(ToolTip widget, Boolean value){
		widget.setVisible(value);
		return null;
	}
}
    