package kr.or.eclipse.swt.query.util;

/*
 * generated by SWT Query SDK at Mon Oct 24 13:53:19 KST 2011
 */ 
import org.eclipse.swt.dnd.DragSource;
import org.eclipse.swt.dnd.DropTarget;
import org.eclipse.swt.widgets.Caret;
import org.eclipse.ui.forms.widgets.ImageHyperlink;
import org.eclipse.ui.forms.widgets.TreeNode;
import org.eclipse.ui.forms.widgets.Twistie;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.ui.forms.widgets.Hyperlink;
import org.eclipse.ui.forms.widgets.ScrolledForm;
import org.eclipse.ui.forms.widgets.ScrolledFormText;
import org.eclipse.ui.forms.widgets.ScrolledPageBook;
import org.eclipse.ui.forms.widgets.Section;
import org.eclipse.ui.forms.widgets.ToggleHyperlink;
import org.eclipse.swt.custom.CLabel;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.custom.TableCursor;
import org.eclipse.swt.opengl.GLCanvas;
import org.eclipse.swt.widgets.Decorations;
import org.eclipse.ui.forms.widgets.AbstractHyperlink;
import org.eclipse.ui.forms.widgets.ExpandableComposite;
import org.eclipse.ui.forms.widgets.FormText;
import org.eclipse.ui.forms.widgets.SharedScrolledComposite;
import org.eclipse.jface.dialogs.ProgressIndicator;
import org.eclipse.jface.wizard.ProgressMonitorPart;
import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.custom.CBanner;
import org.eclipse.swt.custom.CCombo;
import org.eclipse.swt.custom.CTabFolder;
import org.eclipse.swt.custom.SashForm;
import org.eclipse.swt.custom.ScrolledComposite;
import org.eclipse.swt.custom.ViewForm;
import org.eclipse.swt.widgets.Canvas;
import org.eclipse.swt.widgets.Combo;
import org.eclipse.swt.widgets.CoolBar;
import org.eclipse.swt.widgets.DateTime;
import org.eclipse.swt.widgets.ExpandBar;
import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.Spinner;
import org.eclipse.swt.widgets.TabFolder;
import org.eclipse.swt.widgets.Table;
import org.eclipse.swt.widgets.ToolBar;
import org.eclipse.swt.widgets.Tree;
import org.eclipse.ui.dialogs.FilteredList;
import org.eclipse.ui.dialogs.FilteredTree;
import org.eclipse.ui.forms.widgets.Form;
import org.eclipse.ui.part.DrillDownComposite;
import org.eclipse.ui.part.PageBook;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.List;
import org.eclipse.swt.widgets.Text;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Link;
import org.eclipse.swt.widgets.ProgressBar;
import org.eclipse.swt.widgets.Sash;
import org.eclipse.swt.widgets.Scale;
import org.eclipse.swt.widgets.Scrollable;
import org.eclipse.swt.widgets.Slider;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.IME;
import org.eclipse.swt.custom.CTabItem;
import org.eclipse.swt.widgets.CoolItem;
import org.eclipse.swt.widgets.ExpandItem;
import org.eclipse.swt.widgets.MenuItem;
import org.eclipse.swt.widgets.TabItem;
import org.eclipse.swt.widgets.TableColumn;
import org.eclipse.swt.widgets.TableItem;
import org.eclipse.swt.widgets.ToolItem;
import org.eclipse.swt.widgets.TrayItem;
import org.eclipse.swt.widgets.TreeColumn;
import org.eclipse.swt.widgets.TreeItem;
import org.eclipse.swt.widgets.Item;
import org.eclipse.swt.widgets.Menu;
import org.eclipse.swt.widgets.ScrollBar;
import org.eclipse.swt.widgets.ToolTip;
import org.eclipse.swt.widgets.Tracker;
import org.eclipse.swt.widgets.Tray;
import org.eclipse.swt.widgets.Widget;

public class WidgetSwitch<T> {
	public T caseDragSource(DragSource dragSource){		
		return caseWidget(dragSource);
	}
	public T caseDropTarget(DropTarget dropTarget){		
		return caseWidget(dropTarget);
	}
	public T caseCaret(Caret caret){		
		return caseWidget(caret);
	}
	public T caseImageHyperlink(ImageHyperlink imageHyperlink){		
		return caseHyperlink(imageHyperlink);
	}
	public T caseTreeNode(TreeNode treeNode){		
		return caseToggleHyperlink(treeNode);
	}
	public T caseTwistie(Twistie twistie){		
		return caseToggleHyperlink(twistie);
	}
	public T caseShell(Shell shell){		
		return caseDecorations(shell);
	}
	public T caseHyperlink(Hyperlink hyperlink){		
		return caseAbstractHyperlink(hyperlink);
	}
	public T caseScrolledForm(ScrolledForm scrolledForm){		
		return caseSharedScrolledComposite(scrolledForm);
	}
	public T caseScrolledFormText(ScrolledFormText scrolledFormText){		
		return caseSharedScrolledComposite(scrolledFormText);
	}
	public T caseScrolledPageBook(ScrolledPageBook scrolledPageBook){		
		return caseSharedScrolledComposite(scrolledPageBook);
	}
	public T caseSection(Section section){		
		return caseExpandableComposite(section);
	}
	public T caseToggleHyperlink(ToggleHyperlink toggleHyperlink){		
		return caseAbstractHyperlink(toggleHyperlink);
	}
	public T caseCLabel(CLabel cLabel){		
		return caseCanvas(cLabel);
	}
	public T caseStyledText(StyledText styledText){		
		return caseCanvas(styledText);
	}
	public T caseTableCursor(TableCursor tableCursor){		
		return caseCanvas(tableCursor);
	}
	public T caseGLCanvas(GLCanvas gLCanvas){		
		return caseCanvas(gLCanvas);
	}
	public T caseDecorations(Decorations decorations){		
		return caseCanvas(decorations);
	}
	public T caseAbstractHyperlink(AbstractHyperlink abstractHyperlink){		
		return caseCanvas(abstractHyperlink);
	}
	public T caseExpandableComposite(ExpandableComposite expandableComposite){		
		return caseCanvas(expandableComposite);
	}
	public T caseFormText(FormText formText){		
		return caseCanvas(formText);
	}
	public T caseSharedScrolledComposite(SharedScrolledComposite sharedScrolledComposite){		
		return caseScrolledComposite(sharedScrolledComposite);
	}
	public T caseProgressIndicator(ProgressIndicator progressIndicator){		
		return caseComposite(progressIndicator);
	}
	public T caseProgressMonitorPart(ProgressMonitorPart progressMonitorPart){		
		return caseComposite(progressMonitorPart);
	}
	public T caseBrowser(Browser browser){		
		return caseComposite(browser);
	}
	public T caseCBanner(CBanner cBanner){		
		return caseComposite(cBanner);
	}
	public T caseCCombo(CCombo cCombo){		
		return caseComposite(cCombo);
	}
	public T caseCTabFolder(CTabFolder cTabFolder){		
		return caseComposite(cTabFolder);
	}
	public T caseSashForm(SashForm sashForm){		
		return caseComposite(sashForm);
	}
	public T caseScrolledComposite(ScrolledComposite scrolledComposite){		
		return caseComposite(scrolledComposite);
	}
	public T caseViewForm(ViewForm viewForm){		
		return caseComposite(viewForm);
	}
	public T caseCanvas(Canvas canvas){		
		return caseComposite(canvas);
	}
	public T caseCombo(Combo combo){		
		return caseComposite(combo);
	}
	public T caseCoolBar(CoolBar coolBar){		
		return caseComposite(coolBar);
	}
	public T caseDateTime(DateTime dateTime){		
		return caseComposite(dateTime);
	}
	public T caseExpandBar(ExpandBar expandBar){		
		return caseComposite(expandBar);
	}
	public T caseGroup(Group group){		
		return caseComposite(group);
	}
	public T caseSpinner(Spinner spinner){		
		return caseComposite(spinner);
	}
	public T caseTabFolder(TabFolder tabFolder){		
		return caseComposite(tabFolder);
	}
	public T caseTable(Table table){		
		return caseComposite(table);
	}
	public T caseToolBar(ToolBar toolBar){		
		return caseComposite(toolBar);
	}
	public T caseTree(Tree tree){		
		return caseComposite(tree);
	}
	public T caseFilteredList(FilteredList filteredList){		
		return caseComposite(filteredList);
	}
	public T caseFilteredTree(FilteredTree filteredTree){		
		return caseComposite(filteredTree);
	}
	public T caseForm(Form form){		
		return caseComposite(form);
	}
	public T caseDrillDownComposite(DrillDownComposite drillDownComposite){		
		return caseComposite(drillDownComposite);
	}
	public T casePageBook(PageBook pageBook){		
		return caseComposite(pageBook);
	}
	public T caseComposite(Composite composite){		
		return caseScrollable(composite);
	}
	public T caseList(List list){		
		return caseScrollable(list);
	}
	public T caseText(Text text){		
		return caseScrollable(text);
	}
	public T caseButton(Button button){		
		return caseControl(button);
	}
	public T caseLabel(Label label){		
		return caseControl(label);
	}
	public T caseLink(Link link){		
		return caseControl(link);
	}
	public T caseProgressBar(ProgressBar progressBar){		
		return caseControl(progressBar);
	}
	public T caseSash(Sash sash){		
		return caseControl(sash);
	}
	public T caseScale(Scale scale){		
		return caseControl(scale);
	}
	public T caseScrollable(Scrollable scrollable){		
		return caseControl(scrollable);
	}
	public T caseSlider(Slider slider){		
		return caseControl(slider);
	}
	public T caseControl(Control control){		
		return caseWidget(control);
	}
	public T caseIME(IME iME){		
		return caseWidget(iME);
	}
	public T caseCTabItem(CTabItem cTabItem){		
		return caseItem(cTabItem);
	}
	public T caseCoolItem(CoolItem coolItem){		
		return caseItem(coolItem);
	}
	public T caseExpandItem(ExpandItem expandItem){		
		return caseItem(expandItem);
	}
	public T caseMenuItem(MenuItem menuItem){		
		return caseItem(menuItem);
	}
	public T caseTabItem(TabItem tabItem){		
		return caseItem(tabItem);
	}
	public T caseTableColumn(TableColumn tableColumn){		
		return caseItem(tableColumn);
	}
	public T caseTableItem(TableItem tableItem){		
		return caseItem(tableItem);
	}
	public T caseToolItem(ToolItem toolItem){		
		return caseItem(toolItem);
	}
	public T caseTrayItem(TrayItem trayItem){		
		return caseItem(trayItem);
	}
	public T caseTreeColumn(TreeColumn treeColumn){		
		return caseItem(treeColumn);
	}
	public T caseTreeItem(TreeItem treeItem){		
		return caseItem(treeItem);
	}
	public T caseItem(Item item){		
		return caseWidget(item);
	}
	public T caseMenu(Menu menu){		
		return caseWidget(menu);
	}
	public T caseScrollBar(ScrollBar scrollBar){		
		return caseWidget(scrollBar);
	}
	public T caseToolTip(ToolTip toolTip){		
		return caseWidget(toolTip);
	}
	public T caseTracker(Tracker tracker){		
		return caseWidget(tracker);
	}
	public T caseTray(Tray tray){		
		return caseWidget(tray);
	}
	public T caseWidget(Widget widget){		
		return null;
	}
	public T doSwitch(Widget widget) {
		if(widget instanceof DragSource){
			return caseDragSource((DragSource)widget);
		}
		else if(widget instanceof DropTarget){
			return caseDropTarget((DropTarget)widget);
		}
		else if(widget instanceof Caret){
			return caseCaret((Caret)widget);
		}
		else if(widget instanceof ImageHyperlink){
			return caseImageHyperlink((ImageHyperlink)widget);
		}
		else if(widget instanceof TreeNode){
			return caseTreeNode((TreeNode)widget);
		}
		else if(widget instanceof Twistie){
			return caseTwistie((Twistie)widget);
		}
		else if(widget instanceof Shell){
			return caseShell((Shell)widget);
		}
		else if(widget instanceof Hyperlink){
			return caseHyperlink((Hyperlink)widget);
		}
		else if(widget instanceof ScrolledForm){
			return caseScrolledForm((ScrolledForm)widget);
		}
		else if(widget instanceof ScrolledFormText){
			return caseScrolledFormText((ScrolledFormText)widget);
		}
		else if(widget instanceof ScrolledPageBook){
			return caseScrolledPageBook((ScrolledPageBook)widget);
		}
		else if(widget instanceof Section){
			return caseSection((Section)widget);
		}
		else if(widget instanceof ToggleHyperlink){
			return caseToggleHyperlink((ToggleHyperlink)widget);
		}
		else if(widget instanceof CLabel){
			return caseCLabel((CLabel)widget);
		}
		else if(widget instanceof StyledText){
			return caseStyledText((StyledText)widget);
		}
		else if(widget instanceof TableCursor){
			return caseTableCursor((TableCursor)widget);
		}
		else if(widget instanceof GLCanvas){
			return caseGLCanvas((GLCanvas)widget);
		}
		else if(widget instanceof Decorations){
			return caseDecorations((Decorations)widget);
		}
		else if(widget instanceof AbstractHyperlink){
			return caseAbstractHyperlink((AbstractHyperlink)widget);
		}
		else if(widget instanceof ExpandableComposite){
			return caseExpandableComposite((ExpandableComposite)widget);
		}
		else if(widget instanceof FormText){
			return caseFormText((FormText)widget);
		}
		else if(widget instanceof SharedScrolledComposite){
			return caseSharedScrolledComposite((SharedScrolledComposite)widget);
		}
		else if(widget instanceof ProgressIndicator){
			return caseProgressIndicator((ProgressIndicator)widget);
		}
		else if(widget instanceof ProgressMonitorPart){
			return caseProgressMonitorPart((ProgressMonitorPart)widget);
		}
		else if(widget instanceof Browser){
			return caseBrowser((Browser)widget);
		}
		else if(widget instanceof CBanner){
			return caseCBanner((CBanner)widget);
		}
		else if(widget instanceof CCombo){
			return caseCCombo((CCombo)widget);
		}
		else if(widget instanceof CTabFolder){
			return caseCTabFolder((CTabFolder)widget);
		}
		else if(widget instanceof SashForm){
			return caseSashForm((SashForm)widget);
		}
		else if(widget instanceof ScrolledComposite){
			return caseScrolledComposite((ScrolledComposite)widget);
		}
		else if(widget instanceof ViewForm){
			return caseViewForm((ViewForm)widget);
		}
		else if(widget instanceof Canvas){
			return caseCanvas((Canvas)widget);
		}
		else if(widget instanceof Combo){
			return caseCombo((Combo)widget);
		}
		else if(widget instanceof CoolBar){
			return caseCoolBar((CoolBar)widget);
		}
		else if(widget instanceof DateTime){
			return caseDateTime((DateTime)widget);
		}
		else if(widget instanceof ExpandBar){
			return caseExpandBar((ExpandBar)widget);
		}
		else if(widget instanceof Group){
			return caseGroup((Group)widget);
		}
		else if(widget instanceof Spinner){
			return caseSpinner((Spinner)widget);
		}
		else if(widget instanceof TabFolder){
			return caseTabFolder((TabFolder)widget);
		}
		else if(widget instanceof Table){
			return caseTable((Table)widget);
		}
		else if(widget instanceof ToolBar){
			return caseToolBar((ToolBar)widget);
		}
		else if(widget instanceof Tree){
			return caseTree((Tree)widget);
		}
		else if(widget instanceof FilteredList){
			return caseFilteredList((FilteredList)widget);
		}
		else if(widget instanceof FilteredTree){
			return caseFilteredTree((FilteredTree)widget);
		}
		else if(widget instanceof Form){
			return caseForm((Form)widget);
		}
		else if(widget instanceof DrillDownComposite){
			return caseDrillDownComposite((DrillDownComposite)widget);
		}
		else if(widget instanceof PageBook){
			return casePageBook((PageBook)widget);
		}
		else if(widget instanceof Composite){
			return caseComposite((Composite)widget);
		}
		else if(widget instanceof List){
			return caseList((List)widget);
		}
		else if(widget instanceof Text){
			return caseText((Text)widget);
		}
		else if(widget instanceof Button){
			return caseButton((Button)widget);
		}
		else if(widget instanceof Label){
			return caseLabel((Label)widget);
		}
		else if(widget instanceof Link){
			return caseLink((Link)widget);
		}
		else if(widget instanceof ProgressBar){
			return caseProgressBar((ProgressBar)widget);
		}
		else if(widget instanceof Sash){
			return caseSash((Sash)widget);
		}
		else if(widget instanceof Scale){
			return caseScale((Scale)widget);
		}
		else if(widget instanceof Scrollable){
			return caseScrollable((Scrollable)widget);
		}
		else if(widget instanceof Slider){
			return caseSlider((Slider)widget);
		}
		else if(widget instanceof Control){
			return caseControl((Control)widget);
		}
		else if(widget instanceof IME){
			return caseIME((IME)widget);
		}
		else if(widget instanceof CTabItem){
			return caseCTabItem((CTabItem)widget);
		}
		else if(widget instanceof CoolItem){
			return caseCoolItem((CoolItem)widget);
		}
		else if(widget instanceof ExpandItem){
			return caseExpandItem((ExpandItem)widget);
		}
		else if(widget instanceof MenuItem){
			return caseMenuItem((MenuItem)widget);
		}
		else if(widget instanceof TabItem){
			return caseTabItem((TabItem)widget);
		}
		else if(widget instanceof TableColumn){
			return caseTableColumn((TableColumn)widget);
		}
		else if(widget instanceof TableItem){
			return caseTableItem((TableItem)widget);
		}
		else if(widget instanceof ToolItem){
			return caseToolItem((ToolItem)widget);
		}
		else if(widget instanceof TrayItem){
			return caseTrayItem((TrayItem)widget);
		}
		else if(widget instanceof TreeColumn){
			return caseTreeColumn((TreeColumn)widget);
		}
		else if(widget instanceof TreeItem){
			return caseTreeItem((TreeItem)widget);
		}
		else if(widget instanceof Item){
			return caseItem((Item)widget);
		}
		else if(widget instanceof Menu){
			return caseMenu((Menu)widget);
		}
		else if(widget instanceof ScrollBar){
			return caseScrollBar((ScrollBar)widget);
		}
		else if(widget instanceof ToolTip){
			return caseToolTip((ToolTip)widget);
		}
		else if(widget instanceof Tracker){
			return caseTracker((Tracker)widget);
		}
		else if(widget instanceof Tray){
			return caseTray((Tray)widget);
		}
		else {
			return caseWidget((Widget)widget);
		}
    }
}
    